config/routes.rb
Rails.application.routes.draw do
  resources :user_apps do
    member do
      post 'transfer_record'
    end
  end
  
  resources :articles
  resources :wallets
  resources :applications
  devise_for :users
  root  'home#index'
  get   'home/about'
  get   'home/donate'
  get   'home/contributors'
  get   'home/search'
  get   'application/control', to: "applications#control"
  get   'wallet/control', to: "wallets#control"
  get   'home/control'
  get   'home/clients'
  get   'export', to: "home#export", as:'export'
end

app/models/application.rb
class Application < ApplicationRecord
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_out_path_for scope
    root_path
  end

  def search
    if params[:search].blank? 
      redirect_to root_path and return
    else
      @param = params[:search].downcase
      @results = Application.all.where("lower(title) LIKE :search", search: "%#{@param}%")
    end
  end

end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :set_application, only: %i[ show edit update destroy ]

  # GET /applications or /applications.json
  def index
    @applications = Application.all
  end

  def control
    @applications = Application.all
  end


  # GET /applications/1 or /applications/1.json
  def show
  end

  # GET /applications/new
  def new
    @application = Application.new
  end

  # GET /applications/1/edit
  def edit
  end

  # POST /applications or /applications.json
  def create
    @application = Application.new(application_params)

    respond_to do |format|
      if @application.save
        format.html { redirect_to application_url(@application), notice: "Application was successfully created." }
        format.json { render :show, status: :created, location: @application }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applications/1 or /applications/1.json
  def update
    respond_to do |format|
      if @application.update(application_params)
        format.html { redirect_to application_url(@application), notice: "Application was successfully updated." }
        format.json { render :show, status: :ok, location: @application }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1 or /applications/1.json
  def destroy
    @application.destroy

    respond_to do |format|
      format.html { redirect_to applications_url, notice: "Application was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def application_params
      params.require(:application).permit(:title, :author, :rd, :ca, :cs, :img)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_application.html.erb
  <div id="<%= dom_id application %>">
    <p>
      <strong>Title:</strong>
      <%= application.title %>
    </p>

    <p>
      <%= application.author %>
    </p>

    <p>
      <strong>Release date (year-month-day):</strong>
      <%= application.rd %>
    </p>

    <p>
      <strong>Crack author:</strong>
      <%= application.ca %>
    </p>

    <p>
      <strong>Crack status:</strong>
      <% if application.cs == true %>
      <span style="color: green"> Cracked </span>
      <%else%>
      <span style="color: red"> Not cracked yet </span>
      <%end%>
    </p>

    <p>
      <% if application.img%>
        <%= image_tag application.img, class:"image"%>
      <% end %>
    </p>

    <% if current_page?('/applications') %>
      <p class="show">
        <%= link_to "Show this application", application, class:"link" %>
      </p>
    <% end %>
    </div>

app/views/applications/_form.html.erb
<%= form_with(model: application) do |form| %>
  <% if application.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(application.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
        <% application.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="block">
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div class="block">
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div class="block">
    <%= form.label :rd, style: "display: block" %>
    <%= form.date_field :rd %>
  </div>

  <div class="block">
    <%= form.label :ca, style: "display: block" %>
    <%= form.text_field :ca %>
  </div>

  <div  class="block">
    <%= form.label :cs, style: "display: block" %>
    <%= form.check_box :cs, class: "checkbox" %>
  </div>

  <div class="block">
    <%= form.label :img, style: "display: block" %>
    <%= form.text_field :img %>
  </div>

  <div class="block">
    <%= form.label :size, style: "display: block" %>
    <%= form.text_field :size %>
  </div>

  <div class="block">
    <%= form.label :app_type, style: "display: block" %>
    <%= form.text_field :app_type %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/applications/control.erb
<h1>Applications control panel</h1> <br>


<% if user_signed_in? %>
 
    <div class="container">
        No. of records:  <%= @applications.count %> <br>
        Title of last record: <%= @applications.last.title %> <br>
        Creation of last record: <%= @applications.last.created_at %> <br>

        <hr>
            <%= link_to "Create new record", new_application_url, class: 'link-app', style: 'font-size: 150%' %> <br>
        <hr>

        <div id="applications" style="width: 100%">
            <% @applications.each_slice(3) do |applications| %>
                <%- applications.each do |application| %>
                    <div class="app">
                        <div class="app-left">
                            <%= image_tag application.img, class:"image"%>
                        </div>
                        <div class="app-right">
                            <strong class="author"><%= link_to application.title, application, class: 'link-app' %></strong><br>
                            <div class="mobile-hide"><%= application.author %><br></div>
                            <%= application.rd %><br>
                            Status: 
                            <% if application.cs == true %>
                            <span style="color: green"><strong> Cracked </strong></span>
                            <%else%>
                            <span style="color: red"><strong> Not cracked yet </strong></span>
                            <%end%><br>
                            <div class="mobile-hide">Crack: <%= application.ca %></div>
                        </div>
                    </div>
                <%end%>
            <%end%>
        </div>
<%else%>
    <div class="container">
        Your are currently not logged into Administrator accout.
        Only Administrator accounts can acces these pages. <br>

        <%= link_to "Log in", new_user_session_url, class: 'link-app' %>
    </div>
<%end%>

app/views/applications/edit.html.erb
<%if user_signed_in? %>
<div class="container">  
  <h1>Editing application</h1>

  <%= render "form", application: @application %>

  <br>

  <div>
    <%= link_to "Show this application", @application, class:"link-app" %> |
    <%= link_to "Back to applications", applications_path, class:"link-app" %> |
    <%= link_to "Back to control panel", application_control_path, class:"link-app" %>
  </div>
</div>
<%else%>
    <div class="container">
        Your are currently not logged into Administrator accout.
        Only Administrator accounts can acces these pages. <br>

        <%= link_to "Log in", new_user_session_url, class: 'link-app' %>
    </div>
<%end%>

app/views/applications/index.html.erb
  <p style="color: green"><%= notice %></p>

  <h1 class="apps">Applications</h1> <br>

  <%= form_tag(search_path, :method => "get") do %>
    <div class="input-group">
      <%= search_field_tag :search, params[:search], placeholder: "Title ", class: "form-control" %>
      <%= button_tag "Search for application", :class => 'btn btn-info glyphicon glyphicon-search', :title => nil %>
    </div>
  <% end %>

  <div id="applications">
    <% @applications.each_slice(3) do |applications| %>
          <%- applications.each do |application| %>
            <div class="app">
              <%= application.title%> | <%= link_to "Show details", application, class: 'link-app' %>
            </div>
          <%end%>
    <%end%>
  </div>

app/views/applications/new.html.erb
 <div class="container">
  <h1>New application</h1>

  <%= render "form", application: @application %>

  <br>

  <div>
    <%= link_to "Back to applications", applications_path, class:"link" %>
  </div>
</div>

app/views/applications/search.html.erb
  <%= form_tag(search_path, :method => "get") do %>
    <div class="input-group">
      <%= search_field_tag :search, params[:search], placeholder: "Title ", class: "form-control" %>
      <%= button_tag "Search for application", :class => 'btn btn-info glyphicon glyphicon-search', :title => nil %>
    </div>
  <% end %>


  <div id="applications">
    <% @results.each_slice(3) do |result| %>
    <%- result.each do |application| %> <br>
            <div class="app">
              <%= application.title%> | <%= link_to "Show details", application, class: 'link-app' %>
            </div>
          <%end%>
    <%end%>
  </div>

app/views/applications/show.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <%= render @application %>

  <div class="show-application-container">
    <%= link_to "Back to applications", applications_path, class:"link-app" %> 
    <% if user_signed_in? %> <!-- SHOW THIS OPTIONS ONLY IF USER IS SIGNED IN -->
    <br>
    <%= link_to "Edit this application", edit_application_path(@application), class:"link-app" %>
    <%= button_to "Destroy this application", @application, method: :delete, class: "button" %>
    <% end %>
  </div>
</div>