config/routes.rb
Rails.application.routes.draw do
  resources :user_apps do
    member do
      post 'transfer_record'
    end
  end
  
  resources :articles
  resources :wallets
  resources :applications
  devise_for :users
  root  'home#index'
  get   'home/about'
  get   'home/donate'
  get   'home/contributors'
  get   'home/search'
  get   'application/control', to: "applications#control"
  get   'wallet/control', to: "wallets#control"
  get   'home/control'
  get   'home/clients'
  get   'export', to: "home#export", as:'export'
end

app/controllers/home_controller.rb
require 'csv'

class HomeController < ApplicationController
  def index
    ua = request.user_agent

    client = DeviceDetector.new(ua)

    Usr.create(:browser => client.name, :os => client.os_name, :dev_type => client.device_type)

    @applications = Application.all

    @usrs = Usr.all
  end

  def export
    @data = Application.all
    headers = ['id', 'title', 'author', 'rd', 'ca', 'cs', 'img', 'created_at', 'updated_at', 'size', 'app_type']
    csv_data = CSV.generate(headers: true) do |csv|
      csv << headers
      @data.each do |row|
        csv << [row.id, row.title, row.author, row.rd, row.ca, row.cs, row.img, row.created_at, row.updated_at, row.size, row.app_type]
      end
    end

    send_data csv_data, filename: "apps.csv"
  end

  def clients
    @usrs = Usr.all
  end

  def about
  end

  def donate
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav>
    <%= link_to 'IIC', root_path, class:'nav-element'%>
    <%= link_to 'About Us', home_about_path, class:'nav-element'%>
    <%= link_to 'Donate', wallets_path, class:'nav-element'%>
    <%= link_to 'Articles', articles_path, class:'nav-element'%>
    <%= link_to 'Contribute', user_apps_path, class:'nav-element'%>
    <%if user_signed_in? %>
    <%= link_to 'Control Panel', home_control_path, class:'nav-element'%>
    <%end%>
</nav>

app/views/home/about.html.erb
<div class="container">
<div id="left"> 
        <h2 style="font-family: 'Bebas Neue', cursive;">What is this project?</h2>
        IIC (shorter of "Is it Cracked?") is a website that provides information
        if certain application was cracked. What makes us different from for example
        CrackWatch is fact that we are not restricting ourselves to only one platform
        or type of software.
    <br>
        <h2 style="font-family: 'Bebas Neue', cursive;">Why this project was created?</h2>
        IIC was created to replace CrackWatch after it was taken down. I simply wanted
        a place where I could go to check if some software that I am interested in has been
        cracked already. And there are websites that show that information but there often
        show only specific type of software (for example games only) or are restricted to
        only one distribution platform (for example steam).
    <br>
        <h2 style="font-family: 'Bebas Neue', cursive;">How can I help this project?</h2>
        If you have programming knowledge you can go to our github repository and
        commit to the project. If you don't know how to program or you don't want
        to improve IIC from technical standpoint, we are working on feature that would
        allow users to submit their information about application (that will be later verified
        either by other users or admins and mods of this project.) Also you can donate
        some Monero to address provided in donate tab.
    <br>
        <h2 style="font-family: 'Bebas Neue', cursive;">How can I extend the database?</h2>
        To extend the database go to the contribute path, then select new user app, fill the
        data and boom! You have just expanded the database. Now all that's left to do is wait
        for approval from administrators.
    <br>
    <h2 style="font-family: 'Bebas Neue', cursive;">What software types are available?</h2>
         To differentiate software types we have made a simple type value which is represented
        number. Available software types are:<br>
        0 - Video Game <br>
        1 - Video Editor <br>
        2 - 3D Model Editor <br>
        3 - IDE / Text Editor <br>
        4 - Audio / Music Editor <br>
        5 - Ebook <br>
        6 - Virtual Machine Manager <br>
        7 - Image Editor <br>
        8 - Office Suite <br>
        Any other value is shown as "Unknown type"
    <br>
</div>
<div id="right">
    <h2 style="font-family: 'Bebas Neue', cursive;">IIC Development Team</h2>
    ShadowGamer3301 "Zbigniew Przybyła": November 2022 - April 2023 <br>
    Jezyk182: December 2022 - April 2023 <br>
    <br>
    <h2 style="font-family: 'Bebas Neue', cursive;">Contributors</h2>
    Gucio: March 2023 <br>
    kmiaw: April 2023 <br>
    DevShubam: April 2023 <br>
    <h2 style="font-family: 'Bebas Neue', cursive;">Data collection and cookies.</h2>
    We try to collect as little data as possible from our users, however we need to
    collect some data to make website functional. The data we collect amounts to: 
    <ul>
        <li>Your device type</li>
        <li>Your operating system</li>
        <li>Your browser</li>
        <li>Time of the connection</li>
    </ul>
    Also to make website functional for administrators we use:
    <ul>
        <li>Session cookies</li>
    </ul>
    Here you can check report from
    <%= link_to "Cookie-Script.com", "https://cookie-script.com/quick-report?identifier=f2c0e79d73deff6b0c6f510b0b8e054e", class: "link-app" %> <br>
    All data that we've collected is summed up and deleted every two months.
    <br>
    <h2 style="font-family: 'Bebas Neue', cursive;">Useful links.</h2>
    <%= link_to "Github repository", "https://github.com/ShadowGamer3301/IIC", class: "link-app" %> <br>
    </div>
</div>

app/views/home/clients.html.erb
<h1>Clients control panel</h1> <br>


<% if user_signed_in? %>
 
    <div class="container">
        No. of records:  <%= @usrs.count %> <br>
        Creation of last record: <%= @usrs.last.created_at %> <br>

        <div id="applications" style="width: 100%">
            <% @usrs.each_slice(3) do |usrs| %>
                <%- usrs.each do |usr| %>
                    <div class="app">
                    <%= usr.browser%> | <%= usr.os%> | <%= usr.dev_type%> | <%= usr.created_at%>
                    </div>
                <%end%>
            <%end%>
        </div>
<%else%>
    <div class="container">
        Your are currently not logged into Administrator accout.
        Only Administrator accounts can acces these pages. <br>

        <%= link_to "Log in", new_user_session_url, class: 'link-app' %>
    </div>
<%end%>

app/views/home/contributors.erb
<div class="container">
  <h2 style="font-family: 'Bebas Neue', cursive;">IIC Development Team</h2>
  ShadowGamer3301 "Zbigniew Przybyła": 2022-2023 <br>
  Jezyk182: 2022-2023 <br>
</div>
<br>
<div class="container">
  <h2 style="font-family: 'Bebas Neue', cursive;">Distinguished Contributors</h2>
  (Contributors that provided major changes/improvements to project) <br>
</div>
<br>
<div class="container">
  <h2 style="font-family: 'Bebas Neue', cursive;">Normal contributors</h2>
  (Contributors that provided minor or indirect changes/improvements to project) <br>
  Gucio: 2023 <br>
</div>

app/views/home/control.html.erb
<h1>Administrator control panel</h1> <br>

<% if user_signed_in? %>
    <div class="container">
        <h1>Manage</h1> <br>
        <%= link_to "Close session", destroy_user_session_path, data: { turbo_method: :delete }, class: 'link-app' %> <br>
        <%= link_to "Check ZCash balance", "https://explorer.zcha.in/accounts/t1gtCmWyc7kw4SSixrHdftjEUzvZAxPXTQb", class: 'link-app' %> <br>
        <%= link_to "Check Github repository", "https://github.com/ShadowGamer3301/IIC", class: 'link-app' %> <br>
        <%= link_to "AWS managment", "https://signin.aws.amazon.com/signin?redirect_uri=https%3A%2F%2Feu-west-1.console.aws.amazon.com%2Fec2%2Fhome%3Fregion%3Deu-west-1%26state%3DhashArgs%2523Instances%253A%26isauthcode%3Dtrue&client_id=arn%3Aaws%3Aiam%3A%3A015428540659%3Auser%2Fec2&forceMobileApp=0&code_challenge=HN6EbF5BEzc64frxmQlr0oGZEJodlxs-d3yg65QedKs&code_challenge_method=SHA-256", class: 'link-app'%> <br>
        <%= link_to "Domain managment", "https://www.namecheap.com/", class: 'link-app'%> <br>
        <%= link_to "Change account details", edit_user_registration_path , class: 'link-app'%> <br>
    </div>

    <br>

    <div class="container">
        <h1>Control panels</h1> <br>
        <%= link_to "Applications control panel", application_control_path, class: 'link-app' %> <br>
        <%= link_to "Wallets control panel", wallet_control_path, class: 'link-app' %> <br>
        <%= link_to "Clients control panel", home_clients_path, class: 'link-app' %> <br>
    </div>

<%else%>
    <div class="container">
        Your are currently not logged into Administrator accout.
        Only Administrator accounts can acces these pages. <br>

        <%= link_to "Log in", new_user_session_url, class: 'link-app' %>
    </div>
<%end%>

app/views/home/index.html.erb
<div class="container IIC">
  <div id="IIC-header">
    <h1>Is It Cracked?</h1>
    <p>Database of cracked software</p>
    <p>With <%= @usrs.count %> visits</p>
  </div>


  We have built this project as free and open sourced, so anyone can enjoy and
  improve it. Yet some things are not free, such as servers, domains, etc.
  We want to offer you the best experience without the need for serving you ads, or
  collecting and selling your data to 3rd-party companies. So we would be
  very happy if you would consider donating and helping us maintain this project. <br> 
  <p id="IICDT">Is It Cracked DevTeam</p>

</div>

<div class="apps-con">
  <div id="search">
      <%= form_tag(home_search_path, :method => "get") do %>
    <div class="input-group">
      <%= search_field_tag :search, params[:search], placeholder: "Title ", class: "form-control" %>
      <%= button_tag "Search for application", :class => 'btn button btn-info glyphicon glyphicon-search', :title => nil %><br>
    </div>
  <% end %>
  </div><br>
<div id="applications">
    <% @applications.each_slice(3) do |applications| %>
          <%- applications.each do |application| %>
            <div class="app">
              <div class="app-left">
                <%= image_tag application.img, class:"image"%>
              </div>
              <div class="app-right">
                <strong class="author"><%= application.title %></strong><br>
                <div class="mobile-hide"><%= application.author %><br></div>
                <%= application.rd %><br>
                Status: 
                <% if application.cs == true %>
                <span style="color: green"><strong> Cracked </strong></span>
                <%else%>
                <span style="color: red"><strong> Not cracked yet </strong></span>
                <%end%><br>
                <div class="mobile-hide">Crack: <%= application.ca %></div>
              </div>
            </div>
          <%end%>
    <%end%>
</div>
</div>

<footer>
    <h2 style="font-family: 'Bebas Neue', cursive; position: fixed; bottom: 5px; width: 100%;" class="footer">This website uses cookies. More details are in About Us tab.</h2>
</footer>

app/views/home/search.html.erb
<div class="apps-con">
  <div id="search">
      <%= form_tag(home_search_path, :method => "get") do %>
    <div class="input-group">
      <%= search_field_tag :search, params[:search], placeholder: "Title ", class: "form-control" %>
      <%= button_tag "Search for application", :class => 'btn btn-info glyphicon glyphicon-search', :title => nil %>
    </div>
  <% end %>
  </div><br>
<div id="applications">
    <% @results.each_slice(3) do |applications| %>
          <%- applications.each do |application| %>
            <div class="app">
              <div class="app-left">
                <%= image_tag application.img, class:"image"%>
              </div>
              <div class="app-right">
                <strong><%= application.title %></strong><br>
                <%= application.author %><br>
                <%= application.rd %><br><br>
                Status: 
                <% if application.cs == true %>
                <span style="color: green"> Cracked </span>
                <%else%>
                <span style="color: red"> Not cracked yet </span>
                <%end%><br>
                Crack: <%= application.ca %>
              </div>
            </div>
          <%end%>
    <%end%>
</div>
</div>