config/routes.rb
Rails.application.routes.draw do
  resources :user_apps do
    member do
      post 'transfer_record'
    end
  end
  
  resources :articles
  resources :wallets
  resources :applications
  devise_for :users
  root  'home#index'
  get   'home/about'
  get   'home/donate'
  get   'home/contributors'
  get   'home/search'
  get   'application/control', to: "applications#control"
  get   'wallet/control', to: "wallets#control"
  get   'home/control'
  get   'home/clients'
  get   'export', to: "home#export", as:'export'
end

app/models/user_app.rb
class UserApp < ApplicationRecord
end

app/controllers/user_apps_controller.rb
class UserAppsController < ApplicationController
  before_action :set_user_app, only: %i[ show edit update destroy ]

  # GET /user_apps or /user_apps.json
  def index
    @user_apps = UserApp.all
  end

  # GET /user_apps/1 or /user_apps/1.json
  def show
  end

  # GET /user_apps/new
  def new
    @user_app = UserApp.new
  end

  # GET /user_apps/1/edit
  def edit
  end

  # POST /user_apps or /user_apps.json
  def create
    @user_app = UserApp.new(user_app_params)

    respond_to do |format|
      if @user_app.save
        format.html { redirect_to user_app_url(@user_app), notice: "User app was successfully created." }
        format.json { render :show, status: :created, location: @user_app }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_apps/1 or /user_apps/1.json
  def update
    respond_to do |format|
      if @user_app.update(user_app_params)
        format.html { redirect_to user_app_url(@user_app), notice: "User app was successfully updated." }
        format.json { render :show, status: :ok, location: @user_app }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_apps/1 or /user_apps/1.json
  def destroy
    @user_app.destroy

    respond_to do |format|
      format.html { redirect_to user_apps_url, notice: "User app was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def transfer_record
    record_to_transfer = UserApp.find(params[:id])
    new_record = Application.new(record_to_transfer.attributes.except('id', 'created_at', 'updated_at'))
    if new_record.save
      record_to_transfer.destroy
      redirect_to new_record, notice: "Record transferred successfully"
    else
      redirect_to record_to_transfer, alert: "Transfer failed"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_app
      @user_app = UserApp.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_app_params
      params.require(:user_app).permit(:title, :author, :rd, :ca, :cs, :img, :size, :app_type)
    end
end

app/helpers/user_apps_helper.rb
module UserAppsHelper
end

app/views/user_apps/_form.html.erb
<%= form_with(model: user_app) do |form| %>
  <% if user_app.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user_app.errors.count, "error") %> prohibited this user_app from being saved:</h2>

      <ul>
        <% user_app.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    Software title:
    <%= form.text_field :title %>
  </div>

  <div>
    Software author: 
    <%= form.text_field :author %>
  </div>

  <div>
    Release date: 
    <%= form.date_field :rd %>
  </div>

  <div>
    Crack author: 
    <%= form.text_field :ca %>
  </div>

  <div>
    Cracked: 
    <%= form.check_box :cs %>
  </div>

  <div>
    Image URL:
    <%= form.text_field :img %>
  </div>

  <div>
    Game size (GB): 
    <%= form.text_field :size %>
  </div>

  <div>
    Software type:
    <%= form.number_field :app_type %>
    <%=link_to "Software types", home_about_path, class: 'link-app'%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/user_apps/_user_app.html.erb
<div id="<%= dom_id user_app %>">
  <p>
    <strong>Title:</strong>
    <%= user_app.title %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= user_app.author %>
  </p>

  <p>
    <strong>Rd:</strong>
    <%= user_app.rd %>
  </p>

  <p>
    <strong>Ca:</strong>
    <%= user_app.ca %>
  </p>

  <p>
    <strong>Cs:</strong>
    <%= user_app.cs %>
  </p>

  <p>
    <strong>Img:</strong>
    <%= user_app.img %>
  </p>

  <p>
    <strong>Size:</strong>
    <%= user_app.size %>
  </p>

  <p>
    <strong>App type:</strong>
    <%= user_app.app_type %>
  </p>

</div>

app/views/user_apps/edit.html.erb
<h1>Editing user app</h1>

<%= render "form", user_app: @user_app %>

<br>

<div>
  <%= link_to "Show this user app", @user_app %> |
  <%= link_to "Back to user apps", user_apps_path %>
</div>

app/views/user_apps/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>User apps</h1>

<%= link_to "New user app", new_user_app_path, class: 'link-app' %> <br>
Waitaing for approval: <br>
<%if user_signed_in?%>
<div id="applications">
    <% @user_apps.each_slice(3) do |user_apps| %>
          <%- user_apps.each do |user_app| %>
            <div class="app">
              <div class="app-left">
                <%= image_tag user_app.img, class:"image"%>
              </div>
              <div class="app-right">
                <strong class="author"><%= user_app.title %></strong><br>
                <div class="mobile-hide"><%= user_app.author %><br></div>
                <%= user_app.rd %><br>
                Status: 
                <% if user_app.cs == true %>
                <span style="color: green"><strong> Cracked </strong></span>
                <%else%>
                <span style="color: red"><strong> Not cracked yet </strong></span>
                <%end%><br>
                <div class="mobile-hide">Crack: <%= user_app.ca %></div>
                <%= button_to 'Transfer Record', transfer_record_user_app_url(user_app), method: :post%>
              </div>
            </div>
          <%end%>
    <%end%>
</div>
<%else%>
    <% @user_apps.each_slice(3) do |user_apps| %>
          <%- user_apps.each do |user_app| %>
            <%= user_app.title%> by <%= user_app.author%> <br>
          <%end%>
    <%end%>
<%end%>

app/views/user_apps/new.html.erb
<h1>New user app</h1>

<%= render "form", user_app: @user_app %>

<br>

<div>
  <%= link_to "Back to user apps", user_apps_path, class: 'link-app' %>
</div>

app/views/user_apps/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user_app %>

<div>
  <%= link_to "Back to user apps", user_apps_path %>
<%if user_signed_in?%>
  <%= link_to "Edit this user app", edit_user_app_path(@user_app) %>
  <%= button_to "Destroy this user app", @user_app, method: :delete %>
<%end%>
</div>